print("Git is a bit tricky to learn at first, but it's very powerful.")
print("Hello, world!")
print("Bye, see you next time!")
print("This is a simple Python script.")
print("Modify symbol is visible this time :)")
print("I am trying this in feature1 branch. It should appear only in this branch.")
print("It should not appear in main branch.")
